## A Hands-on Workshop series in Machine Learning
#### Instructor: Dr. Aashita Kesarwani

### Background

We know the input vectors in the Bag-Of-Words (BOW) methods have a very high dimension (that is the same as the size of the vocabulary). Autoencoder neural networks are one of the simplest way to reduce the dimension for the input vectors. There are several neural networks, most prominently the family of word2vec algorithms, that are more efficient and useful for this purpose but we will study autoencoder as they are the simplest and easiest to understand the word embeddings.

### Autoencoder neural networks

Autoencoder neural networks create a bottleneck to compress data.

![](https://www.jeremyjordan.me/content/images/2018/03/Screen-Shot-2018-03-06-at-3.17.13-PM.png)

For training the autoencoders, we set the output $y$ to be the same as the input $x$. So, for the above network, we can use the following training set:
* x1 = y1 = [1, 0, 0, 0, 0, 0]
* x2 = y2 = [0, 1, 0, 0, 0, 0]
* x3 = y3 = [0, 0, 1, 0, 0, 0]
* x4 = y4 = [0, 0, 0, 1, 0, 0]
* x5 = y5 = [0, 0, 0, 0, 1, 0]
* x6 = y6 = [0, 0, 0, 0, 0, 1]

If we train the above network for several epochs, the hidden layer will learn a representation of the data in a lower dimension. We can use the output of the hidden layer to reduce the dimension of the input vector (in the above case, the dimension is reduced from 6 to 3).

In [2]:
from keras.models import Sequential, Model
from keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from keras import losses
import numpy as np

from keras.utils import set_random_seed
set_random_seed(1)

X = np.eye(6)
Y = X

print(X)

2023-11-10 14:20:33.222634: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [3]:
model = Sequential()
model.add(Dense(units=3, input_dim=6, activation="sigmoid")) # Hidden layer
model.add(Dense(units=6, activation="softmax")) # Output layer
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 21        
                                                                 
 dense_1 (Dense)             (None, 6)                 24        
                                                                 
Total params: 45
Trainable params: 45
Non-trainable params: 0
_________________________________________________________________


2023-11-10 14:21:06.453755: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
opt = Adam(learning_rate=0.008, beta_1=0.9, beta_2=0.999)
model.compile(optimizer=opt, loss="categorical_crossentropy", metrics=["accuracy"])
model.fit(X, Y, epochs=350, verbose=1); 

Epoch 1/350
1/1 [==============================] - 0s 241ms/step - loss: 1.8971 - accuracy: 0.1667
Epoch 2/350
1/1 [==============================] - 0s 2ms/step - loss: 1.8881 - accuracy: 0.1667
Epoch 3/350
1/1 [==============================] - 0s 1ms/step - loss: 1.8794 - accuracy: 0.1667
Epoch 4/350
1/1 [==============================] - 0s 1ms/step - loss: 1.8712 - accuracy: 0.1667
Epoch 5/350
1/1 [==============================] - 0s 1ms/step - loss: 1.8634 - accuracy: 0.1667
Epoch 6/350
1/1 [==============================] - 0s 1ms/step - loss: 1.8560 - accuracy: 0.1667
Epoch 7/350
1/1 [==============================] - 0s 1ms/step - loss: 1.8490 - accuracy: 0.1667
Epoch 8/350
1/1 [==============================] - 0s 1ms/step - loss: 1.8424 - accuracy: 0.1667
Epoch 9/350
1/1 [==============================] - 0s 1ms/step - loss: 1.8363 - accuracy: 0.1667
Epoch 10/350
1/1 [==============================] - 0s 2ms/step - loss: 1.8305 - accuracy: 0.1667
Epoch 11/350
1/1 [=========

1/1 [==============================] - 0s 1ms/step - loss: 1.5446 - accuracy: 0.6667
Epoch 85/350
1/1 [==============================] - 0s 3ms/step - loss: 1.5387 - accuracy: 0.6667
Epoch 86/350
1/1 [==============================] - 0s 2ms/step - loss: 1.5327 - accuracy: 0.6667
Epoch 87/350
1/1 [==============================] - 0s 2ms/step - loss: 1.5267 - accuracy: 0.6667
Epoch 88/350
1/1 [==============================] - 0s 1ms/step - loss: 1.5206 - accuracy: 0.6667
Epoch 89/350
1/1 [==============================] - 0s 2ms/step - loss: 1.5144 - accuracy: 0.6667
Epoch 90/350
1/1 [==============================] - 0s 2ms/step - loss: 1.5082 - accuracy: 0.6667
Epoch 91/350
1/1 [==============================] - 0s 2ms/step - loss: 1.5019 - accuracy: 0.6667
Epoch 92/350
1/1 [==============================] - 0s 3ms/step - loss: 1.4955 - accuracy: 0.6667
Epoch 93/350
1/1 [==============================] - 0s 2ms/step - loss: 1.4892 - accuracy: 0.6667
Epoch 94/350
1/1 [===============

1/1 [==============================] - 0s 1ms/step - loss: 0.9917 - accuracy: 0.8333
Epoch 168/350
1/1 [==============================] - 0s 1ms/step - loss: 0.9860 - accuracy: 0.8333
Epoch 169/350
1/1 [==============================] - 0s 1ms/step - loss: 0.9804 - accuracy: 0.8333
Epoch 170/350
1/1 [==============================] - 0s 1ms/step - loss: 0.9749 - accuracy: 0.8333
Epoch 171/350
1/1 [==============================] - 0s 1ms/step - loss: 0.9694 - accuracy: 0.8333
Epoch 172/350
1/1 [==============================] - 0s 1ms/step - loss: 0.9639 - accuracy: 0.8333
Epoch 173/350
1/1 [==============================] - 0s 1ms/step - loss: 0.9585 - accuracy: 0.8333
Epoch 174/350
1/1 [==============================] - 0s 1ms/step - loss: 0.9532 - accuracy: 0.8333
Epoch 175/350
1/1 [==============================] - 0s 1ms/step - loss: 0.9479 - accuracy: 0.8333
Epoch 176/350
1/1 [==============================] - 0s 1ms/step - loss: 0.9426 - accuracy: 0.8333
Epoch 177/350
1/1 [=====

1/1 [==============================] - 0s 1ms/step - loss: 0.6535 - accuracy: 0.8333
Epoch 250/350
1/1 [==============================] - 0s 1ms/step - loss: 0.6503 - accuracy: 0.8333
Epoch 251/350
1/1 [==============================] - 0s 1ms/step - loss: 0.6472 - accuracy: 0.8333
Epoch 252/350
1/1 [==============================] - 0s 1ms/step - loss: 0.6441 - accuracy: 0.8333
Epoch 253/350
1/1 [==============================] - 0s 1ms/step - loss: 0.6410 - accuracy: 0.8333
Epoch 254/350
1/1 [==============================] - 0s 1ms/step - loss: 0.6380 - accuracy: 0.8333
Epoch 255/350
1/1 [==============================] - 0s 1ms/step - loss: 0.6349 - accuracy: 0.8333
Epoch 256/350
1/1 [==============================] - 0s 1ms/step - loss: 0.6319 - accuracy: 0.8333
Epoch 257/350
1/1 [==============================] - 0s 1ms/step - loss: 0.6289 - accuracy: 0.8333
Epoch 258/350
1/1 [==============================] - 0s 1ms/step - loss: 0.6258 - accuracy: 0.8333
Epoch 259/350
1/1 [=====

1/1 [==============================] - 0s 1ms/step - loss: 0.4572 - accuracy: 0.8333
Epoch 332/350
1/1 [==============================] - 0s 1ms/step - loss: 0.4555 - accuracy: 0.8333
Epoch 333/350
1/1 [==============================] - 0s 1ms/step - loss: 0.4539 - accuracy: 0.8333
Epoch 334/350
1/1 [==============================] - 0s 1ms/step - loss: 0.4522 - accuracy: 0.8333
Epoch 335/350
1/1 [==============================] - 0s 2ms/step - loss: 0.4506 - accuracy: 0.8333
Epoch 336/350
1/1 [==============================] - 0s 1ms/step - loss: 0.4489 - accuracy: 0.8333
Epoch 337/350
1/1 [==============================] - 0s 1ms/step - loss: 0.4473 - accuracy: 0.8333
Epoch 338/350
1/1 [==============================] - 0s 1ms/step - loss: 0.4457 - accuracy: 0.8333
Epoch 339/350
1/1 [==============================] - 0s 1ms/step - loss: 0.4441 - accuracy: 0.8333
Epoch 340/350
1/1 [==============================] - 0s 2ms/step - loss: 0.4425 - accuracy: 0.8333
Epoch 341/350
1/1 [=====

Let's see the weights connecting the input to the hidden layer.

In [5]:
hidden_layer_weights = model.layers[0].get_weights()[0]
hidden_layer_weights

array([[ 2.3535373 ,  1.7600238 ,  2.6751099 ],
       [-2.479652  ,  0.6684221 , -1.6248617 ],
       [ 1.9789417 , -3.3325272 ,  1.6378893 ],
       [-2.6733994 ,  2.0745368 , -3.1317546 ],
       [ 0.88372207, -2.8770435 , -2.793328  ],
       [-3.196977  ,  1.483793  ,  2.7325883 ]], dtype=float32)

Let's create a new neural network that discards the output layer effectively making the output of the hidden layer as the final output. We can use this model for reducing the dimension for word embeddings.

In [6]:
hidden_layer_model = Model(inputs=model.input, 
                           outputs=model.get_layer(index=0).output)
hidden_layer_output = hidden_layer_model(X)
hidden_layer_output

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[0.92892784, 0.9086109 , 0.9448164 ],
       [0.09424649, 0.76944655, 0.18852136],
       [0.8998663 , 0.0575537 , 0.8585264 ],
       [0.07895716, 0.93158555, 0.04896059],
       [0.7503575 , 0.08784174, 0.06735086],
       [0.04832941, 0.8829389 , 0.94773775]], dtype=float32)>

Let's round up the final output. The input X in our case was the identity matrix. Each row in the output corresponds to reduced dimensional representation of the 6-dimensional identity vectors.

In [7]:
np.round(hidden_layer_output, decimals=2)

array([[0.93, 0.91, 0.94],
       [0.09, 0.77, 0.19],
       [0.9 , 0.06, 0.86],
       [0.08, 0.93, 0.05],
       [0.75, 0.09, 0.07],
       [0.05, 0.88, 0.95]], dtype=float32)

In [20]:
x = np.array([4,2,10,4,8,6]).reshape(1,6)
np.round(hidden_layer_model(x), decimals=2)

array([[0.84, 0.  , 1.  ]], dtype=float32)

#### Further reading
* [Introduction to autoencoders](https://www.jeremyjordan.me/autoencoders)

* [Deep learning book (Chapter 14): Autoencoders](https://www.deeplearningbook.org/contents/autoencoders.html)

### Word embeddings

Word embeddings are simply representations of words as numerical vectors. Several word embedding techniques such as word2vec, autoencoders (seen above) and BERT (Bidirectional Encoder Representations from Transformers) are neural network based representations. The neural networks are trained on a choosen text corpus to generate the word representations. 

BERT involves transformer models that we will study today.

#### Word2vec embedding

Word2vec embeddings are a class of sevaral models that are used to generate word embedding. They were first introduced by Mikolov, et al. in [Efficient Estimation of Word Representations in
Vector Space](https://arxiv.org/pdf/1301.3781.pdf). They can be used as the first step in the neural network to create lower-dimensional vectorization for textual data as compared to count/TFIDF vectorization methods while storing information about the relationship between the words.

The embedding space for word2vec is an n-dimensional vector space where each word has a corresponding vector in the space. The arrangement of vectors corresponding to words in the embedding space stores useful information concerning the relationship between the words. For example, the difference in vectors corresponding to France and Paris would be similar to difference between Italy and Rome.

$$ vec(France) - vec(Paris) = vec(Italy) - vec(Rome)$$

The neural networks learn these relationships on their own based on the corpus used to train them. The vector words that occur together often in the corpus have vectors that are similar in mathematical sense.

Learning word representations is an unsupervised task, so we need some way to create the (input, target) pairs. Similar to autoencoders, the neural networks are trained for a fake task but once trained, the output layer is discarded and the trained weights are to used to map words into vectors. 

<img align="center" src="http://mccormickml.com/assets/word2vec/word2vec_weight_matrix_lookup_table.png" width=500 >

The above word2vec representation reduces the dimension from 10,000 to 300. There are several trained word2vec algorithms available that you can directly use to generate embeddings. 

The fake task that is used to generate the word embeddings are slightly different for the different models in the word2vec family. Two of the most commonly used ones are:

* Continuous Skip-gram Model
* Continuous Bag-of-Words Model (CBOW)

#### Further reading

* [Word2Vec Tutorial - The Skip-Gram Model](http://www.mccormickml.com)
